### ISSUE TITLE
github CI: add PR

### ISSUE THREAD

**Issue by vtorri** [michaelforney/samurai#89]
Add PR support for CI, like:

```
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]
```

this allows to check if a PR compiles or not before pushing it. Imho, it's a very important feature to check is a PR does not break compilation or tests

do you want a PR ?
